package view;

import service.GerenciadorTarefas;
import model.Tarefa;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JScrollPane;

public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    private GerenciadorTarefas gerenciador = new GerenciadorTarefas();
    
    private javax.swing.JList<String> listaTarefas;
    private javax.swing.DefaultListModel<String> modeloLista;
    
    public TelaPrincipal() {
        initComponents();
                      
        modeloLista = new DefaultListModel<>();
        jList1.setModel(modeloLista);
        
        gerenciador.carregar();   
        atualizarLista();         
        atualizarStatus();        
        
    }
    
    private void atualizarLista(){
        modeloLista.clear();
        
        String filtro = (String) comboFiltro.getSelectedItem();
        if (filtro == null) {
            filtro = "Todas";
        }
        
        List<Tarefa> tarefas = gerenciador.getTarefas();
        
        for (Tarefa t: tarefas) {
            if (filtro.equals("Todas")) {
                modeloLista.addElement(t.toString()); 
            } else if (filtro.equals("Pendentes") && !t.isConcluida() && !t.isEmAndamento()) {
                modeloLista.addElement(t.toString()); 
            } else if (filtro.equals("Em Andamento") && t.isEmAndamento()) {
                modeloLista.addElement(t.toString()); 
            } else if (filtro.equals("Concluídas") && t.isConcluida()) {
                modeloLista.addElement(t.toString()); 
            }
            
        }
    }
    
    private void atualizarStatus(){

        int total = gerenciador.contarTotal();
        int concluidas = gerenciador.contarConcluidas();
        int andamento = gerenciador.contarEmAndamento();

        String texto = String.format(
            "Total: %d  |  [~] Em andamento: %d  |  [X] Concluídas: %d",
            total, andamento, concluidas
        );

        labelStatus.setText(texto);
        labelStatus.setText(labelStatus.getText() + " ");
        
        labelStatus.revalidate();
        labelStatus.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextNovaTarefa = new javax.swing.JTextField();
        buttonAdd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        buttonConcluir = new javax.swing.JButton();
        buttonRemover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        buttonComecar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        buttonEditar = new javax.swing.JButton();
        buttonPrioridade = new javax.swing.JButton();
        buttonLimpar = new javax.swing.JButton();
        buttonSubir = new javax.swing.JButton();
        buttonDescer = new javax.swing.JButton();
        comboFiltro = new javax.swing.JComboBox<>();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/checked - Copia.png"))); // NOI18N
        jLabel2.setText("ToDoList");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Tarefa:");

        TextNovaTarefa.setForeground(new java.awt.Color(204, 204, 204));
        TextNovaTarefa.setText("Nova Tarefa");
        TextNovaTarefa.addActionListener(this::TextNovaTarefaActionPerformed);

        buttonAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonAdd.setText("Adicionar");
        buttonAdd.addActionListener(this::buttonAddActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Lista De Tarefas");

        buttonConcluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonConcluir.setText("Concluir");
        buttonConcluir.addActionListener(this::buttonConcluirActionPerformed);

        buttonRemover.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonRemover.setText("Remover");
        buttonRemover.addActionListener(this::buttonRemoverActionPerformed);

        jList1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jList1.setForeground(new java.awt.Color(0, 0, 102));
        jScrollPane1.setViewportView(jList1);

        buttonComecar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonComecar.setText("Começar");
        buttonComecar.addActionListener(this::buttonComecarActionPerformed);

        labelStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelStatus.setText("---------------");

        buttonEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonEditar.setText("Editar");
        buttonEditar.addActionListener(this::buttonEditarActionPerformed);

        buttonPrioridade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonPrioridade.setText("Prioridade");
        buttonPrioridade.addActionListener(this::buttonPrioridadeActionPerformed);

        buttonLimpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonLimpar.setText("Limpar");
        buttonLimpar.addActionListener(this::buttonLimparActionPerformed);

        buttonSubir.setText("▲");
        buttonSubir.addActionListener(this::buttonSubirActionPerformed);

        buttonDescer.setText("▼");
        buttonDescer.addActionListener(this::buttonDescerActionPerformed);

        comboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Pendentes", "Em Andamento", "Concluídas" }));
        comboFiltro.addActionListener(this::comboFiltroActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonComecar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonEditar)
                                .addGap(18, 18, 18)
                                .addComponent(buttonConcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonRemover)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonPrioridade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonLimpar)
                                .addContainerGap(35, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonAdd)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextNovaTarefa))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSubir)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonDescer)
                        .addContainerGap())))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(353, Short.MAX_VALUE))
            .addComponent(labelStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextNovaTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAdd)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(labelStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(buttonSubir)
                        .addGap(18, 18, 18)
                        .addComponent(buttonDescer))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(comboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonConcluir)
                    .addComponent(buttonRemover)
                    .addComponent(buttonComecar)
                    .addComponent(buttonEditar)
                    .addComponent(buttonPrioridade)
                    .addComponent(buttonLimpar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextNovaTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNovaTarefaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNovaTarefaActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        System.out.println("clicou no adicionar");
        
        String descricao = TextNovaTarefa.getText();
        
        if (descricao.isBlank()){
            return;
        }
        
        System.out.println("texto digitado: " + descricao);
        
        gerenciador.adicionar(descricao);
        
        TextNovaTarefa.setText("");
        
        atualizarLista();
        atualizarStatus();
        gerenciador.salvar();
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConcluirActionPerformed
        
        int indice = jList1.getSelectedIndex();
        
        if (indice == -1){
            return;
        }
        
            
        gerenciador.concluir(indice);
  
        atualizarLista();
        atualizarStatus();
        gerenciador.salvar();
    }//GEN-LAST:event_buttonConcluirActionPerformed

    private void buttonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverActionPerformed
        int indice = jList1.getSelectedIndex();
        
        if (indice == -1) {
            return;
        }
        
        gerenciador.remover(indice);
        
        atualizarLista();
        atualizarStatus();
        gerenciador.salvar();
    }//GEN-LAST:event_buttonRemoverActionPerformed

    private void buttonComecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonComecarActionPerformed
        int indice = jList1.getSelectedIndex();
        
        if (indice == -1){
            return;
        }
        
        gerenciador.comecar(indice);
        
        atualizarLista();
        atualizarStatus();
        gerenciador.salvar();
        
    }//GEN-LAST:event_buttonComecarActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        int indice = jList1.getSelectedIndex();
        
        if (indice == -1){
            return;
        }
        
        List<Tarefa> tarefas = gerenciador.getTarefas();
        Tarefa tarefaSelecionada = tarefas.get(indice);
        
        String novaDescricao = javax.swing.JOptionPane.showInputDialog(
            this, 
            "Edite a descrição da tarefa:", 
            tarefaSelecionada.getDescricao()
        );
        
        if (novaDescricao == null || novaDescricao.isBlank()) {
            return;
        }
        
        gerenciador.editar(indice, novaDescricao);
        
        atualizarLista();
        atualizarStatus();
        gerenciador.salvar();
        
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void buttonPrioridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrioridadeActionPerformed
        int indice = jList1.getSelectedIndex();
    
        // Se não tiver nenhuma tarefa selecionada, avisa o usuário
        if (indice == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma tarefa primeiro!");
            return;
        }

        // Lista de opções que vão aparecer para o usuário escolher
        String[] opcoes = {"Alta", "Média", "Baixa"};

        // Abre uma janelinha com botões de escolha (caixa de seleção)
        String escolha = (String) javax.swing.JOptionPane.showInputDialog(
            this,
            "Escolha o nível de prioridade para esta tarefa:",
            "Definir Prioridade",
            javax.swing.JOptionPane.QUESTION_MESSAGE,
            null,
            opcoes,
            opcoes[1] // Deixa "Média" selecionado por padrão
        );

        // Se o usuário não cancelou a janelinha, atualiza a prioridade
        if (escolha != null) {
            gerenciador.mudarPrioridade(indice, escolha);

            // Atualiza a tela e salva no arquivo .txt
            atualizarLista();
            atualizarStatus();
            gerenciador.salvar();
        }
    }//GEN-LAST:event_buttonPrioridadeActionPerformed

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
        // Abre uma janelinha perguntando se o usuário tem certeza
        int resposta = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "Tem certeza que deseja apagar TODAS as tarefas?", 
            "Confirmar Limpeza", 
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        // Se a resposta for SIM (YES_OPTION), a gente limpa tudo
        if (resposta == javax.swing.JOptionPane.YES_OPTION) {
            gerenciador.limparTudo(); // Esvazia a lista

            // Atualiza a tela e salva o arquivo em branco
            atualizarLista();
            atualizarStatus();
            gerenciador.salvar();
        }
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void buttonSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubirActionPerformed
        int indice = jList1.getSelectedIndex();
        
        if (indice == -1){
            return;
        }
        
        gerenciador.moverParaCima(indice);
        
        atualizarLista();
        
        if (indice > 0) {
            jList1.setSelectedIndex(indice - 1);
        }
        
        gerenciador.salvar();
    }//GEN-LAST:event_buttonSubirActionPerformed

    private void buttonDescerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDescerActionPerformed
        int indice = jList1.getSelectedIndex();
        
        if (indice == -1) {
            return;
        }
        
        gerenciador.moverParaDescer(indice);
        
        atualizarLista();
        
        if (indice > 0) {
            jList1.setSelectedIndex(indice + 1);
        }
        
        gerenciador.salvar();
    }//GEN-LAST:event_buttonDescerActionPerformed

    private void comboFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFiltroActionPerformed
        atualizarLista();
    }//GEN-LAST:event_comboFiltroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextNovaTarefa;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonComecar;
    private javax.swing.JButton buttonConcluir;
    private javax.swing.JButton buttonDescer;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton buttonPrioridade;
    private javax.swing.JButton buttonRemover;
    private javax.swing.JButton buttonSubir;
    private javax.swing.JComboBox<String> comboFiltro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelStatus;
    // End of variables declaration//GEN-END:variables
}
